import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

import Head from "next/head";
import Image from "next/image";
import CursorLight from "@/components/CursorLight";
import Header from "../components/Header";
import { CartProvider } from "@/context/CartContext";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MOL-D",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <link rel="preload" as="image" href="/fundo_hero.jpg" />
      </Head>
      <html
        lang="pt-br"
        className={`${poppins.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <CartProvider>
            <Header />
            <Image
              src="/fundo_hero.jpg"
              alt=""
              fill
              priority
              className="hero-image object-cover"
            />
            <CursorLight />


            {children}
          </CartProvider>
          <div className="noise-overlay" aria-hidden="true" />
        </body>
      </html>
    </>

  );
}
